name: Rust

on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: hecrj/setup-rust-action@master
        with:
          rust-version: nightly
      - name: Check Cargo availability
        run: cargo --version
      - name: Check Rustup default toolchain
        run: rustup default | grep nightly

      - name: Build
        run: |
          env RUSTFLAGS="-C link-arg=-s" cargo build --release
          mkdir doh-proxy
          mv target/release/doh-proxy doh-proxy/
          cp README.md doh-proxy/
      - uses: actions/upload-artifact@master
        with:
          name: doh-proxy-linux-x86_64
          path: doh-proxy

